
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-scrape-config
  namespace: monitoring
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: otel-collector
        scrape_interval: 5s
        static_configs:
          - targets: ['otel-collector.monitoring.svc.cluster.local:8889']
      - job_name: spring-actuator
        metrics_path: /actuator/prometheus
        scrape_interval: 5s
        static_configs:
          - targets: ['petclinic.petclinic.svc.cluster.local:9464']
