
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  rules.yaml: |
    groups:
      - name: example
        rules:
          - alert: InstanceDown
            expr: up == 0
            for: 1m
