apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: c:\utils\kompose\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mysqlserver
  name: mysqlserver
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysqlserver
