apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: monitoring
data:
  COLLECTOR_OTLP_ENABLED: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.53 # usar una versión estable en vez de latest
          ports:
            - containerPort: 4317 # OTLP gRPC
            - containerPort: 9411 # Zipkin
            - containerPort: 16686 # Jaeger UI
          envFrom:
            - configMapRef:
                name: jaeger-config

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: ui
      port: 16686
      targetPort: 16686
  type: ClusterIP
