apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-loki-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki-config.yaml: |
    # Este es un ejemplo básico de configuración para Loki
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    distributor:
      ring:
        kvstore:
          store: inmemory
    ingester:
      max_transfer_retries: 0
    querier:
      engine:
        query_timeout: 1m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-config-volume
              mountPath: /etc/loki/loki-config.yaml
              subPath: loki-config.yaml
            - name: data-loki
              mountPath: /loki
      volumes:
        - name: loki-config-volume
          configMap:
            name: loki-config
        - name: data-loki
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app: loki