repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: mysql
    namespace: petclinic
    chart: bitnami/mysql
    values:
      - mysql-values.yaml

  - name: petclinic
    namespace: petclinic
    chart: ./petclinic

  - name: argocd
    namespace: argocd
    chart: bitnami/argo-cd

  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    values:
      - prometheus-values.yaml
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "./monitoring/prometheus-configmap.yaml"]
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "./monitoring/prometheus-rules-configmap.yaml"]

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - grafana-values.yaml
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "./monitoring/grafana-dashboard-configmap.yaml"]

  - name: loki
    namespace: monitoring
    chart: grafana/loki-stack
    values:
      - loki-values.yaml
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "./monitoring/loki-configmap.yaml"]
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "./monitoring/promtail-configmap.yaml"]

  - name: tempo
    namespace: monitoring
    chart: grafana/tempo
    values:
      - tempo-values.yaml
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "./monitoring/tempo-configmap.yaml"]

  - name: otel-collector
    namespace: monitoring
    chart: open-telemetry/opentelemetry-collector
    values:
      - otel-collector-values.yaml
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "./monitoring/otel-configmap.yaml"]
