apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mperezgithub/fc-devops-infraestructure-automation.git # CAMBIA ESTO
    targetRevision: HEAD
    path: k8s/kustomize/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true