apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: c:\utils\kompose\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: petclinic
  name: petclinic
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "9464"
      port: 9464
      targetPort: 9464
  selector:
    io.kompose.service: petclinic
